# dplyr closures and rlang {#ch:rlang}

```{r make-lahman-data}
library(tidyverse)
library(gridExtra)
batting <- as_tibble(Lahman::Batting)
fielding <- as_tibble(Lahman::Fielding)

is_col <- names(batting)[c(1, 2, 4, 6:17)]
is_num <- names(batting)[sapply(batting, is.numeric)]
gt_500 <- batting %>%
  select(is_col) %>%
  select(-teamID) %>% 
  drop_na() %>%
  group_by(playerID) %>% 
  summarize_at(is_col[-(1:3)], sum, na.rm = T) %>% 
  filter(G >= 500)
is_field = names(fielding)[c(1, 6, 7, 10, 11, 12, 13)]
pos_tot <- fielding %>%
  select(is_field) %>% 
  drop_na() %>% 
  group_by(playerID, POS) %>%
  summarize_all(sum) %>%
  ungroup() %>% 
  filter(G >= 100) %>% 
  arrange(playerID, desc(G)) %>%
  group_by(playerID) %>% 
  mutate(pos1 = first(POS)) %>% 
  filter(POS == pos1) %>% 
  select(-pos1)
batpos <- gt_500 %>% 
  left_join(pos_tot, by = "playerID")
batpos <- batpos %>% 
  drop_na()
batpos <- batpos %>% 
  mutate(BA = H / AB) %>%  # batting average, hits / at bats
  mutate(Err = E / (PO + A)) %>%   # error rate, errors / (put outs + assists)
  mutate(HRR = HR / AB)  # home run rate, home runs / at bats
```

## Trying to understand the closure functions
Using `example("function")` is _very_ helpful.
```{r}
is_col <- names(select_if(batpos, is.double))
batpos[is_col] <- batpos[is_col] %>%
  map(round, digits = 4)
```

```{r}
batpos %>% 
  select(contains("B"))
```
```{r}
batpos %>% 
  select_all(toupper)
```
```{r}
batpos %>% 
  drop_na() %>% 
  #select_if(function(x) sum(x == 0) > 100, tolower)
  select_if(function(x) sum(x == 0) > 100, tolower)
```
```{r}
batpos %>%
  drop_na() %>% 
  sapply(function(x) sum(x == 0) > 100)
```
```{r}
batpos %>% 
  drop_na() %>% 
  rename_if(function(x) ! sum(x == 0) > 100, tolower)
```
```{r}
batpos %>% 
  select_at(c(2, 4, 6, 8, 10, 12, 14), tolower) %>% 
  rename_at(c(3,5,7), toupper)
```
```{r}
batpos %>% 
#  select_all(toupper)
  select_all(list(~ toupper(.)))
```
```{r}
batpos %>% 
#  select_all(toupper)
#  select_all(list(~ paste(., "0", sep="")))
  select_all(~ paste(., "0", sep=""))
```
```{r}
batpos %>% 
#  select_if(is.numeric, ~ paste(., "new", sep="_"))
  mutate_if(is.numeric, function(x) log(x + 1))
```

```{r}
batpos %>% 
  rename_if(is.numeric, ~ paste(., "N", sep=""))
```

```{r}
batpos %>% 
  rename_at(vars(contains("B")), ~ tolower(.))
```
```{r}
batpos %>% 
  select(contains("B")) %>% 
  rename_all(~ tolower(.))
# or
batpos %>% 
  select_at(vars(contains("B")), ~ tolower(.))
```
```{r}
batpos %>% 
  keep(is.numeric) %>% 
  filter_all(all_vars(. < 1000))
```
```{r}
batpos %>% 
  filter_all(any_vars(. > 10000))
```
```{r}
batpos %>% 
  filter_if(is.numeric, all_vars(. < 600))
```
```{r}
batpos %>% 
  select_at(4:10)
```
```{r}
batpos %>% 
  filter_at(4:6, all_vars((. %% 10) == 5))
```
```{r}
batpos %>% 
  filter_at(vars(starts_with("X")), any_vars((. %% 50) == 0 & . > 0))
```
```{r}
is_whole <- function(x) if(is.numeric(x)) all(floor(x) == x) else FALSE
#batpos %>% 
#  keep(is_whole) %>% 
#  filter_if(~ all(floor(.) == .), any_vars((. %% 100) == 50))
batpos %>% 
  filter_if(is_whole, any_vars((. %% 100) == 50))
```

## Tidy evaluation with rlang

Symbols:
```{r}
library(rlang)
cat(pi, expr(pi), eval(expr(pi)), '\n')
cat(is_symbol(pi), is_symbol(expr(pi)))
```
```{r}
print_types <- function(x) {
  print(x)
  print(eval(x))
  cat('  Symbol:', is_symbol(x))
  cat(' Environment:', is_environment(x))
  cat(' Constant:', is_bare_atomic(x))
  cat('\n  Call object:', is_call(x))
  cat(' Expression:', is_expression(x))
  cat(' Quosure:', is_quosure(x))
  cat('\n')
}
```
```{r}
a <- 1
b <- 2
sapply(c(pi, 1, abs(1), pi, expr(pi), expr(a+b), quo(a+b)),
       print_types)
```
```{r}
quos(a+b, a-b)
```
```{r}
quote_this <- function(x) enquo(x)
quote_these <- function(...) enquos(...)
```

```{r}
# quosures allow code to be written from string variables
# and vice versa
print(1 + eval(parse_expr("a + b")))
print(expr_text(function(x) x^2))
```

